version: 2

sphinx:
   configuration: docs/conf.py

formats: []

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dnspytho
        - pydantic
        - idna
        - requests

build:
  os: ubuntu-24.04
  tools:
    python: "3.11.9"



