version: 2

sphinx:
   configuration: docs/source/conf.py

formats: []

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dnspython
        - pydantic
        - idna
        - requests

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"



